# variables
#   nfs-clients:
#     - host: nfsserver:/mnt/disk1
#       mount_point: /mnt/disk1

---
- name: install autofs
  become: yes
  apt: 
    pkg:
      - autofs 
    state: latest


- name: add direct map
  become: yes
  copy:
    src: user_disk.autofs
    dest: /etc/auto.master.d/user_disk.autofs
    mode: "0644"
  notify: 
    - restart autofs


- name: setup /etc/auto.mount
  become: yes
  template:
    src: auto.user_disk.j2
    dest: /etc/auto.master.d/auto.user_disk
    mode: "0644"
  notify:
    - restart autofs


