---
- name: install apache2
  become: yes
  apt: 
    pkg:
      - apache2
    update_cache: yes 
    cache_valid_time: 3600
    state: latest

- name: start service apache2
  become: yes
  service: 
    name: apache2
    enabled: yes 
    state: started 

- name: apache2 config site
  become: yes
  template: src=site.conf.j2 dest=/etc/apache2/sites-available/site.conf
  notify: restart apache2

- name: apache2 config ssl-site
  become: yes
  template: src=site-ssl.conf.j2 dest=/etc/apache2/sites-available/site-ssl.conf
  notify: restart apache2

- name: disable site 000-default
  become: yes
  command: a2dissite 000-default

- name: disable site default-ssl
  become: yes
  command: a2dissite default-ssl

- name: enable site
  become: yes
  command: a2ensite site

- name: enable site-ssl
  become: yes
  command: a2ensite site-ssl

- name: enable mod_rewirte
  become: yes
  command: a2enmod rewrite

- name: restart service apache2
  become: yes
  service: 
    name: apache2 
    enabled: yes 
    state: restarted

