---
- include_tasks: proteindf-dev-ubuntu1604.yml
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '16.04'

- include_tasks: proteindf-dev-ubuntu1804.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- include_tasks: proteindf-dev-ubuntu2004.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '20.04'

- include_tasks: proteindf-dev-ubuntu2204.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '22.04'


