---
- name: install ProteinDF devtools
  become: yes
  apt:
    pkg: 
      - build-essential
      - libgfortran3
      - libblas-dev
      - liblapack-dev
      - liblapacke-dev
      - libblacs-mpi-dev
      - libscalapack-mpi-dev
      - libatlas-base-dev
      - libopenblas-base
      - libopenblas-dev
      - libeigen3-dev
      - ocl-icd-opencl-dev 
      - libclc-dev 
      - opencl-headers
      - libboost-all-dev
      - libviennacl-dev
      - libhdf5-dev
    force: yes
    update_cache: yes
    state: latest

