# -----------------------------------------------------------------------------
# git
# -----------------------------------------------------------------------------
- name: add packages for git lfs
  become: yes
  apt: 
    pkg:
      - software-properties-common
    update_cache: yes
    state: latest

- name: add apt repository for git lfs
  become: yes
  shell: add-apt-repository -y ppa:git-core/ppa

- name: setup repository for git lfs
  become: yes
  shell: "curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash"

- name: install git-lfs
  become: yes
  apt: 
    pkg: 
      - git-lfs
    update_cache: yes
    state: latest

