- name: install devtools
  become: yes
  apt:
    pkg:
      - build-essential
      - gcc
      - g++
      - libgmp-dev
      - libboost-all-dev
      - gfortran
      - clang
      - libclang-dev
      - golang
      - make
      - automake
      - autoconf
      - libtool
      - cmake
      - pkg-config
      - git
      - global
      - xorg-dev
      - libreadline-dev
      - libncurses5-dev
      - openssl
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev 
      - libsqlite3-dev
      - tk8.5-dev
      - liblzma-dev
      - libeigen3-dev
      - liblapack-dev
      - libpng-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - libyaml-dev
      - libcppunit-dev
      - jq
      - libffi-dev
      - libhdf5-dev
      - hdf5-tools
      - flex
      - bison
      - clisp
      - libgtest-dev
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: update max user watches
  become: yes
  copy:
    src: 60-max-user-watches.conf
    dest: /etc/sysctl.d/60-max-user-watches.conf
  notify: restart procps

