---
# - name: install sysv-rc-conf
#   become: yes
#   apt: pkg={{ item }} force=yes update_cache=yes state=latest
#   with_items:
#     - sysv-rc-conf
- name: install language-pack
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - language-pack-ja

- import_tasks: utils.yml
- import_tasks: systemtools.yml
- import_tasks: shell.yml
- import_tasks: ntp.yml
- import_tasks: editor.yml
- import_tasks: devenv.yml
- import_tasks: devtools.yml
- import_tasks: python.yml
- import_tasks: gdb.yml


- name: set limits
  become: yes
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
