---
# - name: install sysv-rc-conf
#   become: yes
#   apt: pkg={{ item }} force=yes update_cache=yes state=latest
#   with_items:
#     - sysv-rc-conf

- name: install language-pack
  become: yes
  apt: 
    pkg: ['language-pack-ja']
    force: yes
    update_cache: yes
    state: latest

- import_tasks: utils.yml
- import_tasks: systemtools.yml
- import_tasks: shell.yml

- import_tasks: ntp.yml
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- import_tasks: editor.yml
#- include: devenv.yml
#- include: devtools.yml
#- include: python.yml
#- include: gdb.yml


- name: set limits
  become: yes
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
