---
# - name: install sysv-rc-conf
#   become: yes
#   apt: pkg={{ item }} force=yes update_cache=yes state=latest
#   with_items:
#     - sysv-rc-conf
- name: install language-pack
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - language-pack-ja

#- include: ubuntu1404ja.yml
- include: systemtools.yml
- include: shell.yml
- include: ntp.yml
- include: editor.yml
- include: devenv.yml
- include: devtools.yml
- include: python.yml
- include: gdb.yml


- name: set limits
  become: yes
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644
    
