- name: install ntp package
  become: yes
  apt: 
    pkg:
      - ntp
    update_cache: yes
    state: latest

- name: start ntp server
  become: yes
  service: 
    name: ntp
    state: started

- name: copy NTP setting file
  become: yes
  template: 
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    mode: 0644
  notify: restart ntp server

