- name: uninstall ntp package
  become: yes
  apt: 
    pkg:
      - ntp
    state: absent

- name: update NTP setting file
  become: yes
  lineinfile: 
    dest: /etc/systemd/timesyncd.conf
    state: present
    backrefs: True
    regexp: "^#?NTP=*."
    line: "NTP={{ ntp_server }}"
  notify: restart systemd_timesyncd

