- name: install devtools
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - python-dev 
    - python-setuptools
    - python-pip
    - python-sphinx 
    - python-numpy
    - python-scipy
    - python-pandas
    - python-matplotlib 
    - msgpack-python 
    - python-yaml 
    - pep8
    - python-jinja2
    - python-scikits-learn

