- name: install system tools
  become: yes
  apt: 
    pkg: 
      - smartmontools
      - lsof
      - expect 

      - screenfetch
      - neofetch
      - htop
      - btop
      - crazydiskinfo
    state: latest
    
