---
# - name: restart nis server
#   become: yes
#   service: 
#     name: "{{ nis_service_name | default('ypserv') }}"
#     state: restarted


- name: "restart nis server on Ubuntu >= 22"
  become: yes
  service: 
    name: ypserv
    state: restarted
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version | int >= 22
  listen: "restart nis server"

- name: "restart nis server on Ubuntu < 22"
  become: yes
  service: 
    name: nis 
    state: restarted
  when:
    - ansible_distribution == "Ubuntu" 
    - ansible_distribution_major_version | int < 22
  listen: "restart nis server"

  
