---
# https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx
#
#

- include_tasks: radeon-ubuntu1604.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- include_tasks: radeon-ubuntu1804.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04"


- name: install AMD OpenCL env
  become: yes
  apt:
    pkg:
      - opencl-amdgpu-pro-icd
      - clinfo-amdgpu-pro
    state: latest
    update_cache: yes

# https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk
#- name: make temp dir for AMD-APP-SDK
#  become: yes
#  file:
#    path: /tmp/amdappsdk
#    state: directory
#- name: put AMD APP SDK
#  unarchive:
#    src: AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
#    dest: /tmp/amdappsdk/
#- name: install AMD-APP-SDK
#  become: yes
#  shell: "yes | /tmp/amdappsdk/AMD-APP-SDK-v3.0.130.136-GA-linux64.sh"

