---
# https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx
#
#

- name: add arch i386
  become: yes
  shell: dpkg --add-architecture i386

- name: fetch AMD GPU pro driver (ubuntu 16.04)
  get_url:
    url: "https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
    headers: "Referer:https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx"
    dest: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- name: fetch AMD GPU pro driver (ubuntu 18.04)
  get_url:
    url: "https://www2.ati.com/drivers/linux/ubuntu/18.04/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
    headers: "Referer:https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx"
    dest: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04"

- name: unpack AMD GPU pro driver
  become: yes
  unarchive:
    src: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
    dest: /tmp
    remote_src: True

- name: install AMD GPU pro driver
  become: yes
  shell: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}/amdgpu-pro-install -y"

- name: install AMD OpenCL env
  become: yes
  apt:
    pkg:
      - opencl-amdgpu-pro-icd
      - clinfo-amdgpu-pro
    state: latest
    update_cache: yes

# https://developer.amd.com/amd-accelerated-parallel-processing-app-sdk
#- name: make temp dir for AMD-APP-SDK
#  become: yes
#  file:
#    path: /tmp/amdappsdk
#    state: directory
#- name: put AMD APP SDK
#  unarchive:
#    src: AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
#    dest: /tmp/amdappsdk/
#- name: install AMD-APP-SDK
#  become: yes
#  shell: "yes | /tmp/amdappsdk/AMD-APP-SDK-v3.0.130.136-GA-linux64.sh"

