---
- name: install texlive package
  become: yes
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
    - texlive
    - texlive-lang-japanese
    - xdvik-ja
    - dvipsk-ja
    - gv
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-science
    - texlive-math-extra
    
