---
- include_tasks: ubuntu-ja-1404.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "14.04"

- include_tasks: ubuntu-ja-1604.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

#- include_tasks: 'roles/ubuntu-ja/tasks/ubuntu-ja-18.04.yml'
- include_tasks: ubuntu-ja-1804.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04"


