- name: check installed softether
  shell: "test -d {{ softether_root }}/vpnserver"
  register: has_softether
  ignore_errors: yes

# - name: show has_softether
#   debug: 
#     var: has_softether

- name: install packages for softether
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - bridge-utils

- name: download softether
  become: yes
  get_url:
    url: "{{ softether_url }}"
    dest: /tmp/softether.tar.gz
    sha256sum: "{{ softether_sha256sum}}"
    force: True
  when: has_softether.rc != 0

- name: unpack softether package
  become: yes
  command: tar zxvf /tmp/softether.tar.gz -C /usr/local
  when: has_softether.rc != 0

- name: build softether
  become: yes
  shell: "(cd /usr/local/vpnserver; yes 1 | make)"
  when: has_softether.rc != 0

- name: copy softether boot script
  become: yes
  template:
    src: vpnserver.j2
    dest: /etc/init.d/vpnserver
    mode: 0755

- name: register softether boot script
  become: yes
  command: update-rc.d vpnserver defaults



