---
- include_tasks: proteindf-ubuntu1604.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- include_tasks: proteindf-ubuntu1804.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04"
