---
- name: install ProteinDF devtools
  become: yes
  apt:
    pkg:
      - python3-numpy
      - python3-scipy
      - python3-pandas
      - python3-matplotlib
      - python3-sklearn
      - python3-yaml
      - python3-msgpack
      - python3-bs4
      - python3-h5py
      - python3-jinja2

      - libomp5

      - libblas-dev
      - liblapack-dev
      
      - libopenblas-openmp-dev
      - libblis-dev

      - openmpi-common
      - openmpi-bin
      - libscalapack-openmpi-dev

    state: latest

- name: switch libopenblas.so
  become: yes
  community.general.alternatives:
    name: libopenblas.so-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblas.so

- name: switch libopenblas.so.0
  become: yes
  community.general.alternatives:
    name: libopenblas.so.0-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/libopenblas.so.0

- name: switch liblapack.so-x86_64-linux-gnu
  become: yes
  community.general.alternatives:
    name: liblapack.so-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/liblapack.so

- name: switch liblapack.so.3-x86_64-linux-gnu
  become: yes
  community.general.alternatives:
    name: liblapack.so.3-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/liblapack.so.3

- name: switch liblapack.so.3-x86_64-linux-gnu
  become: yes
  community.general.alternatives:
    name: liblapack.so.3-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/liblapack.so.3

- name: switch libblas.so-x86_64-linux-gnu
  become: yes
  community.general.alternatives:
    name: libblas.so-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/libblas.so

- name: switch libblas.so.3-x86_64-linux-gnu
  become: yes
  community.general.alternatives:
    name: libblas.so.3-x86_64-linux-gnu
    path: /usr/lib/x86_64-linux-gnu/openblas-openmp/libblas.so.3




