---
- name: install ProteinDF devtools
  become: yes
  apt:
    pkg:
      - python3-numpy
      - python3-scipy
      - python3-pandas
      - python3-matplotlib
      - python3-sklearn
      - python3-yaml
      - python3-msgpack
      - python3-bs4
      - python3-h5py
      - python3-jinja2

      - libomp5
      - libopenblas0-openmp

      - openmpi-common
      - openmpi-bin
      - libscalapack-openmpi2.1

    state: latest

