---
- name: restart nis service
  become: yes
  service: 
    name: ypserv 
    state: restarted
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version >= "22"

- name: restart nis service 
  become: yes
  service:
    name: nis
    enabled: yes
    state: restarted
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version < "22"

  
