---
- name: download docker installer
  get_url:
    url: "https://get.docker.com"
    dest: "/tmp/docker_install.sh"
    mode: 0755

- name: install docker
  become: yes
  command: "/tmp/docker_install.sh"

