---
- name: update apt sources
  become: yes
  apt: 
    pkg: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest


- name: set GPG key
  become: yes
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    creates: /usr/share/keyrings/docker-archive-keyring.gpg


- name: add apt entry
  become: yes
  shell:
    cmd: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list' 
    creates: /etc/apt/sources.list.d/docker.list


- name: install docker
  become: yes
  apt: 
    pkg:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
      - docker-compose-plugin
    state: latest

