---
- name: mkdir docker image path
  become: yes
  file:
    path: "{{ docker_image_path }}"
    state: directory
    mode: 0711
    
- name: setup docker image path
  become: yes
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "ExecStart="
    line: "ExecStart=/usr/bin/dockerd -H unix:// --data-root {{ docker_image_path }}"
  notify: restart docker server
  changed_when: True
    
- name: start docker daemon
  become: yes
  service: name=docker enabled=yes state=started
  notify: restart docker server

- name: add users to docker group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ item }}"
  with_items: "{{ docker_users }}"
  
