---
- name: check if docker is installed
  shell: which docker 
  register: is_installed_docker
  ignore_errors: yes

# - name: debug 
#   debug:
#     msg: "{{ is_installed_docker }}"

- name: install docker
  become: yes
  shell: "curl -sSL https://get.docker.com | bash"
  when: is_installed_docker.stdout == ''

