---
- name: mkdir docker_data_root
  become: yes
  file:
    path: "{{ docker_data_root }}"
    state: directory
    mode: 0711
   

- name: setup docker image path
  become: yes
  lineinfile:
    dest: /lib/systemd/system/docker.service
    regexp: "ExecStart="
    line: "ExecStart=/usr/bin/dockerd -H unix:// --data-root {{ docker_data_root }}"
  notify: restart docker server
  changed_when: True
    

- name: add users to docker group
  become: yes
  user:
    append: yes
    groups: docker
    name: "{{ item }}"
  with_items: "{{ docker_users }}"
  
