---
#- name: install Docker on various os
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "docker-{{ ansible_lsb.id }}.yml"
#    - "docker-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#    - "docker-{{ ansible_distribution }}.yml"

- include: docker-ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"

- include: docker-Raspbian.yml
  when:
    - ansible_lsb.id == "Raspbian"

- include: docker-storage.yml

- name: add docker group
  become: yes
  user:
    name: "{{ item }}"
    append: yes
    groups: docker
    state: present
  with_items: "{{ docker_users | default([]) }}"

- name: setup insecure repositries
  become: yes
  template:
    src: daemon.json.tmpl
    dest: /etc/docker/daemon.json
  notify: restart docker server

#- name: start docker daemon
#  become: yes
#  service:
#    name: docker
#    # enabled: yes
#    state: started
#  # notify: restart docker server


