---
#- name: install Docker on various os
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "docker-{{ ansible_lsb.id }}.yml"
#    - "docker-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#    - "docker-{{ ansible_distribution }}.yml"

- name: install packages supporting docker
  become: yes
  apt:
    pkg:
      - gnupg2 
      - pass
    state: latest

- include: docker-Ubuntu.yml
  when:
    - ansible_distribution == "Ubuntu"

- include: docker-Raspbian.yml
  when:
    - ansible_lsb.id == "Raspbian"

- include: docker-storage.yml

