---
- name: create resolvconf/resolv.conf.d/base
  become: yes
  template: src=resolvconf_base.j2 dest=/etc/resolvconf/resolv.conf.d/base
  when: "ansible_distribution == 'Ubuntu'"

- name: update resolvconf
  become: yes
  shell: resolvconf -u

