---
- name: install nis client
  become: yes
  apt:
    pkg:
      - nis
    state: latest

- name: edit yp.conf
  become: yes
  ansible.builtin.template:
    src: yp.conf.tmpl
    dest: /etc/yp.conf
  notify: restart nis service

- name: edit nssiwtch.conf for passwd
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^passwd: .*'
    line: 'passwd: compat nis'
  notify: restart nis service

  # - meta: flush_handlers

- name: edit nssiwtch.conf for group
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^group: .*'
    line: 'group: compat nis'
  notify: restart nis service

- name: edit nssiwtch.conf for shadow
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^shadow: .*'
    line: 'shadow: compat nis'
  notify: restart nis service

- name: edit nssiwtch.conf for hosts
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^hosts: .*'
    line: 'hosts: files dns nis'
  notify: restart nis service

- name: edit /etc/passwd
  become: yes
  lineinfile:
    dest: /etc/passwd
    regexp: '^\+'
    line: '+::::::'
  notify: restart nis service

- name: edit /etc/group
  become: yes
  lineinfile:
    dest: /etc/group
    regexp: '^\+'
    line: '+:::'
  notify: restart nis service

- name: edit /etc/shadow
  become: yes
  lineinfile:
    dest: /etc/shadow
    regexp: '^\+'
    line: '+::::::::'
  notify: restart nis service

- name: set /etc/domainname
  become: yes
  template:
    src: domainname.tmpl
    dest: /etc/defaultdomain

- name: enable ypbind service
  become: yes
  service:
    name: ypbind
    state: enabled

- name: start ypbind service
  become: yes
  service:
    name: ypbind
    state: started
  
