---
- name: install nis client
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - nis

- name: edit yp.conf
  become: yes
  lineinfile:
    dest: /etc/yp.conf
    regexp: '^ypserver'
    line: 'ypserver {{ nis_servername }}'
  notify: restart nis service
- name: edit nssiwtch.conf for passwd
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^passwd: .*'
    line: 'passwd: compat nis'
  notify: restart nis service
- name: edit nssiwtch.conf for group
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^group: .*'
    line: 'group: compat nis'
  notify: restart nis service
- name: edit nssiwtch.conf for shadow
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^shadow: .*'
    line: 'shadow: compat nis'
  notify: restart nis service
- name: edit nssiwtch.conf for hosts
  become: yes
  lineinfile:
    dest: /etc/nsswitch.conf
    regexp: '^hosts: .*'
    line: 'hosts: files dns nis'
  notify: restart nis service
- name: edit /etc/passwd
  become: yes
  lineinfile:
    dest: /etc/passwd
    regexp: '^\+'
    line: '+::::::'
  notify: restart nis service
- name: edit /etc/group
  become: yes
  lineinfile:
    dest: /etc/group
    regexp: '^\+'
    line: '+:::'
  notify: restart nis service
- name: edit /etc/shadow
  become: yes
  lineinfile:
    dest: /etc/shadow
    regexp: '^\+'
    line: '+::::::::'
  notify: restart nis service

  
