# {{ nis_securentes_netmask }}         {{ nis_securenets_network }}
# nis_domainname
# nis_servername
---
- name: install nis server
  become: yes
  apt: 
    pkg:
      - nis
    state: latest


- name: edit yp.conf
  become: yes
  template:
    src: yp.conf.tmpl
    dest: /etc/yp.conf
  notify: restart nis server


- name: setup ypserv.securenets
  become: yes
  template: src=ypserv.securenets.tmpl dest=/etc/ypserv.securenets
  notify: restart nis server


- name: setup nis Makefile
  become: yes
  template: src=Makefile.tmpl dest=/var/yp/Makefile
  notify: restart nis server


- name: setup /etc/defaultdomain
  become: yes
  template: 
    src: defaultdomain.tmpl
    dest: /etc/defaultdomain
  notify: restart nis server  


# - name: debug var nis_task
#   debug:
#     msg: "nis_task = {{ nis_task }}"


- name: setup NIS master
  include_tasks: master.yml
  when:
    - nis_task == "master"


- name: setup NIS slave
  include_tasks: slave.yml
  when:
    - nis_task == "slave"


- name: start service rpcbind
  become: yes
  service:
    name: rpcbind
    enabled: yes  
    state: started


- name: start service nis
  become: yes
  service:
    name: ypserv
    enabled: yes
    state: started

