# {{ nis_securentes_netmask }}         {{ nis_securenets_network }}
# nis_domainname
# nis_servername
---
- name: install nis server
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - nis

- name: edit yp.conf
  become: yes
  lineinfile:
    dest: /etc/yp.conf
    regexp: '^ypserver'
    line: 'ypserver {{ nis_servername }}'
  notify: restart nis server
- name: setup ypserv.securenets
  become: yes
  template: src=ypserv.securenets.tmpl dest=/etc/ypserv.securenets
  notify: restart nis server
- name: setup nis Makefile
  become: yes
  template: src=Makefile.tmpl dest=/var/yp/Makefile
  notify: restart nis server

- name: setup nis default
  become: yes
  lineinfile:
    dest: /etc/default/nis
    regexp: "^NISSERVER=*"
    line: "NISSERVER=true"
  notify: restart nis server
    
#- name: initialize nis database
#  become: yes
#  command: /usr/lib/yp/ypinit -m

- name: add NIS group
  become: yes
  group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid }}"
    state: present
  with_dict: "{{ nis_groups | default({}) }}"
    
- name: add NIS users
  become: yes
  user:
    name: "{{ item.key }}"
    groups: "{{ item.value.groups }}"
    group: "{{ item.value.group }}"
    state: present
    uid: "{{ item.value.uid }}"
    home: "{{ item.value.home }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
    createhome: no
  with_dict: "{{ nis_users | default({}) }}"
      
- name: update NIS user password
  become: yes
  user:
    name: "{{ item.key }}"
    password: "{{ item.value.password | password_hash('sha512') }}"
  when:
    - item.value.password is defined
    - item.value.update_password is defined
    - item.value.update_password
  with_dict: "{{ nis_users | default({}) }}"
        
- name: update nis database
  become: yes
  command: make -C /var/yp
  
- name: start service nis
  become: yes
  service:
    name: nis
    enabled: yes
    state: started


