---
- name: prepare grafana 
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common 
      - wget
    state: latest

- name: add grafana key 
  become: yes
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: grafana repo
  become: yes
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: install grafana
  become: yes
  apt:
    pkg:
      - grafana
    state: latest
    update_cache: yes

- name: setup grafana.ini
  become: yes
  template:
    dest: /etc/grafana/grafana.ini
    src: grafana.ini.j2
    owner: root
    group: grafana
    mode: "0640"
  notify:
    - restart grafana

- name: start grafana service
  become: yes
  service:
    name: grafana-server
    state: started


