---
# - name: install sysv-rc-conf
#   become: yes
#   apt: pkg={{ item }} force=yes update_cache=yes state=latest
#   with_items:
#     - sysv-rc-conf

- name: setup timeout for shutdown
  become: yes
  lineinfile: 
    dest: /etc/systemd/system.conf
    state: present
    regexp: '^#?\s*DefaultTimeoutStopSec=90s'
    line: DefaultTimeoutStopSec=10s

# =============================================================================
# limit
# =============================================================================
- name: set limits
  become: yes
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: "0644"


# =============================================================================
# core (apport)
# =============================================================================
- import_tasks: apport.yml


# =============================================================================
# debug
# =============================================================================
- name: check enable debug
  become: yes
  shell: cat /etc/sysctl.d/10-ptrace.conf | grep -E 'kernel.yama.ptrace_scope\s+=\s+\w+' | awk '{ print $3 }'
  register: yama_ptrace_scope
  changed_when: false
  # if you use before ansible-v2.4, enable 'always_run'
  # always_run: yes
  check_mode: no


- name: enable debug
  become: yes
  shell: sed -E 's/kernel.yama.ptrace_scope\s+=\s+\w+/kernel.yama.ptrace_scope = 0/g' /etc/sysctl.d/10-ptrace.conf
  when: yama_ptrace_scope.stdout == 1


# =============================================================================
# VS Code
# =============================================================================
- name: update max user watches
  become: yes
  copy:
    src: 60-max-user-watches.conf
    dest: /etc/sysctl.d/60-max-user-watches.conf
  notify: restart procps


# =============================================================================
# import
# =============================================================================
- import_tasks: chrony.yml
- import_tasks: shell.yml
- import_tasks: systemtools.yml

- import_tasks: python.yml
- import_tasks: ruby.yml



