- name: restart ntp server
  become: yes
  service: 
    name: ntp 
    state: restarted

- name: restart systemd_timesyncd
  become: yes
  service:
    name: "systemd-timesyncd"
    state: restarted

- name: restart chrony server
  become: yes
  service:
    name: chrony
    state: restarted

- name: restart procps
  become: yes
  service:
    name: procps
    state: restarted

