# vars
#   - exports_table:
#     - export_dir: /mnt/disk1
#       clients: *(rw,no_root_squash,no_subtree_check)

- name: install nfs-server
  become: yes
  apt: 
    pkg:
    - nfs-common
    - nfs-kernel-server
    state: latest

- name: create exports
  become: yes
  template: 
    src: exports.j2 
    dest: /etc/exports 

- name: enable rpcbind
  become: yes
  command: "systemctl add-wants multi-user.target rpcbind.service"

- name: enabled nfs-kernel-server
  become: yes
  service: 
    name: nfs-kernel-server 
    enabled: yes

- name: restart nfs-kernel-server
  become: yes
  service: 
    name: nfs-kernel-server 
    state: restarted

