---
- name: disable LightDM
  become: yes
  lineinfile:
    dest: /etc/default/grub
    state: present
    regexp: "^GRUB_CMDLINE_LINUX=.*"
    line: 'GRUB_CMDLINE_LINUX="systemd.unit=multi-user.target"'
    backup: yes
- name: update grub
  become: yes
  shell: update-grub

