---
- name: gridengine-common | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_common }}"
    dest: "/tmp/{{ gridengine_deb_common }}"
- name: gridengine-client | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_client }}"
    dest: "/tmp/{{ gridengine_deb_client }}"
- name: gridengine-master | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_master }}"
    dest: "/tmp/{{ gridengine_deb_master }}"
- name: gridengine-qmon | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_qmon }}"
    dest: "/tmp/{{ gridengine_deb_qmon }}"

- name: install gridengine-common
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_common }}"
- name: install gridengine-client
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_client }}"
- name: install gridengine-master
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_master }}"
- name: install gridengine-qmon
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_qmon }}"

