---
- name: install watchdog
  become: yes
  apt:
    pkg: 
      - watchdog
    state: latest

- name: setup watchdog.conf
  become: yes
  template:
    src: watchdog.conf.templ
    dest: /etc/watchdog.conf
  notify: restart watchdog server

