---
- name: install system packages
  become: yes
  apt:
    pkg: "{{ item }}"
    force: yes
    update_cache: yes
    state: latest
  with_items:
    - git
    - rsync
    - gawk
    - busybox
    - bindfs
    - htop
    - lsof
    - ruby
