---
- name: install prometheus
  become: yes
  apt:
    pkg:
      - prometheus
    state: latest

- name: setup args for prometheus
  become: yes
  lineinfile:
    path: /etc/default/prometheus
    regexp: '^ARGS=".*"'
    line: 'ARGS="--web.enable-admin-api"'
    state: present
  notify:
    - restart prometheus server

- name: setup prometheus.yml
  become: yes
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    force: yes
  notify: restart prometheus server

- name: start prometheus service
  become: yes
  service:
    name: prometheus 
    state: started

