---
- name: install dnsmasq
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - dnsmasq

- name: create dnsmasq.conf
  become: yes
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
  notify: service dnsmasq
  
- name: start service dnsmasq
  become: yes
  service: name=dnsmasq enabled=yes state=started
