---
- name: install packages for r8168
  become: yes
  apt: 
    pkg:
      - linux-headers-generic
      - build-essential
      - dkms
      - r8168-dkms
    state: latest

- name: add blacklist
  become: yes
  copy:
    src: blacklist-r8169.conf
    dest: /etc/modprobe.d/blacklist-r8169.conf

# - name: remove modules
#   become: yes
#   command: "modprobe -rfv r8169"
#   ignore_errors: yes

# - name: update modules
#   become: yes
#   command: "modprobe -v r8168"

- name: update initramfs
  become: yes
  command:
    cmd: update-initramfs -u

