---
- name: install Docker compose on various os
  include_vars: "{{ item }}"
  with_first_found:
    - "vars-{{ ansible_system }}-{{ ansible_machine }}.yml"

- name: install docker-compose
  become: yes
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-{{ docker_system }}-{{ docker_machine }}"
    dest: "/usr/local/bin/docker-compose"
    force: yes
    mode: "a+x"

