---
- name: install Munin node
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - munin-node

- name: set munin-node.conf
  become: yes
  template:
    src: munin-node.conf.j2
    dest: /etc/munin/munin-node.conf
  notify: restart munin node
    
- name: start munin node
  become: yes
  service:
    name: "munin-node"
    enabled: yes
    state: started
    
