---
# - name: fetch AMD GPU pro driver
#  shell: >
#    curl -o "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
#    -e "http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx"
#    "https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"

- name: fetch AMD GPU pro driver
  get_url:
    url: "https://www2.ati.com/drivers/linux/ubuntu/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
    headers: "Referer:http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx"
    dest: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
#- name: make temp dir for amdgpu
#  become: yes
#  file:
#    path: /tmp/amdgpu-pro
#    state: directory
- name: unpack AMD GPU pro driver
  become: yes
  unarchive:
    src: "/tmp/amdgpu-pro-{{ amdgpu_driver_version }}.tar.xz"
    dest: /tmp
    remote_src: True
- name: install AMD GPU pro driver
  become: yes
  shell: "/tmp/mdgpu-pro-{{ amdgpu_driver_version }}/amdgpu-pro-install -y"

# http://developer.amd.com/tools-and-sdks/opencl-zone/amd-accelerated-parallel-processing-app-sdk/
- name: make temp dir for AMD-APP-SDK
  become: yes
  file:
    path: /tmp/amdappsdk
    state: directory
- name: put AMD APP SDK
  unarchive:
    src: AMD-APP-SDKInstaller-v3.0.130.136-GA-linux64.tar.bz2
    dest: /tmp/amdappsdk/
- name: install AMD-APP-SDK
  become: yes
  shell: "yes | /tmp/amdappsdk/AMD-APP-SDK-v3.0.130.136-GA-linux64.sh"

