---
- name: update users
  become: yes
  user: 
    name: "{{ item.user }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    password: "{{ item.password }}"
    # password: "{{ item.value.password | password_hash('sha512') }}"
    shell: "{{ item.value.shell | default('/bin/bash') }}"
    createhome: "{{ item.createhome | default('no') }}"
    state: present
  with_items: "{{ my_users }}"
  # ignore_errors: yes

