---
- name: install ProteinDF devtools
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - build-essential
    - libblas-dev
    - liblapack-dev
    - liblapacke-dev
    - libblacs-mpi-dev
    - libscalapack-mpi-dev

