---
- name: restart slurmd
  become: yes
  ansible.builtin.service:
    name: slurmd
    state: restarted

- name: reload slurmctld
  become: yes
  ansible.builtin.service:
    name: slurmctld
    state: reloaded

- name: restart slurmctld
  become: yes
  ansible.builtin.service:
    name: slurmctld
    state: restarted
