- name: update main repo
  become: yes
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic restricted universe multiverse
    state: present

- name: update security repo
  become: yes
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic-security restricted universe multiverse
    state: present

- name: update update repo
  become: yes
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic-updates restricted universe multiverse
    state: present

