---
- name: install prometheus node exporter
  become: yes
  apt:
    pkg:
      - prometheus-node-exporter
    state: latest

- name: start prometheus node exporter service
  become: yes
  service:
    name: prometheus-node-exporter
    state: started


