---
# tasks file for github-cli

- name: Ensure wget is installed
  become: yes
  apt:
    name: wget
    state: present
    update_cache: yes

- name: Ensure /etc/apt/keyrings directory exists
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download GitHub CLI GPG key
  become: yes
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /etc/apt/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
    force: yes

- name: Ensure /etc/apt/sources.list.d directory exists
  become: yes
  file:
    path: /etc/apt/sources.list.d
    state: directory
    mode: '0755'

- name: Add GitHub CLI apt repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ ansible_architecture | lower }} signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github-cli
    state: present
    update_cache: yes

- name: Install GitHub CLI
  become: yes
  apt:
    name: gh
    state: present
