- name: install devtools
  become: yes
  apt: pkg={{ item }} force=yes update_cache=yes state=latest
  with_items:
    - electric-fence
    - ddd
    - git
    - git-flow
    - tig
    - subversion
    - doxygen
    - graphviz
    - google-perftools
    - libgoogle-perftools-dev
    - libgtest-dev

- name: check libgtest
  shell: "ls /usr/lib/libgtest.a /usr/lib/libgtest_main.a"
  register: has_libgtest
  ignore_errors: yes
  #changed_when: false
  #failed_when: false

- debug:
    msg: "{{ has_libgtest }}"

- copy:
    src: build_gtest.sh
    dest: /tmp/build_gtest.sh
    mode: 0755
  when: has_libgtest.failed

- name: build Google Test
  become: yes
  shell: /tmp/build_gtest.sh
  when: has_libgtest.failed
