- name: install devtools
  become: yes
  apt: 
    pkg:
      - build-essential
      - gfortran
      - libboost-all-dev
      - cmake
      - clang-format
      - doxygen
      - graphviz
      - electric-fence
      - ddd
      - google-perftools
      - libgoogle-perftools-dev
      - libgtest-dev
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - ruby
      - sysstat
    state: latest

# - include_tasks: pyenv.yml

# -----------------------------------------------------------------------------
# git
# -----------------------------------------------------------------------------
- name: install git
  become: yes
  apt:
    pkg:
      - git
      - git-lfs
      - git-flow
      - tig
    state: latest

