- name: install devtools
  become: yes
  apt: 
    pkg:
      - build-essential
      - gfortran
      - cmake
      - subversion
      - clang-format
      - doxygen
      - graphviz
      - electric-fence
      - ddd
      - google-perftools
      - libgoogle-perftools-dev
      - libgtest-dev
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
  update_cache: yes
  state: latest

- include_tasks: pyenv.yml

# -----------------------------------------------------------------------------
# git
# -----------------------------------------------------------------------------
- name: install devtools
  become: yes
  apt:
    pkg:
      - git
      - git-flow
      - tig
  update_cache: yes
  state: latest

- include_tasks: git-lfs-ubuntu1604.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- name: install git-lfs
  become: yes
  apt:
    pkg: ['git-lfs']
    force: yes
    update_cache: yes
    state: latest
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04" 
    
# -----------------------------------------------------------------------------
# google test
# -----------------------------------------------------------------------------
#- name: check libgtest
#  shell: "ls /usr/lib/libgtest.a /usr/lib/libgtest_main.a"
#  register: has_libgtest
#  ignore_errors: yes
#  #changed_when: false
#  #failed_when: false
#
#- debug:
#    msg: "{{ has_libgtest }}"
#
#- copy:
#    src: build_gtest.sh
#    dest: /tmp/build_gtest.sh
#    mode: 0755
#  when: has_libgtest.failed
#
#- name: build Google Test
#  become: yes
#  shell: /tmp/build_gtest.sh
#  when: has_libgtest.failed
