---
- name: gridengine-common | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_common }}"
    dest: "/tmp/{{ gridengine_deb_common }}"
- name: gridengine-client | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_client }}"
    dest: "/tmp/{{ gridengine_deb_client }}"
- name: gridengine-exec | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_exec }}"
    dest: "/tmp/{{ gridengine_deb_exec }}"

- name: install gridengine-common
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_common }}"
- name: install gridengine-client
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_client }}"
- name: install gridengine-exec
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_exec }}"

