---
#- name: install gridengine client
#  become: yes
#  apt: pkg={{ item }} force=yes update_cache=yes state=latest
#  with_items:
#    - gridengine-client
#    - gridengine-exec

- name: gridengine-common | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_common }}"
    dest: "/tmp/{{ gridengine_deb_common }}"
- name: gridengine-client | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_client }}"
    dest: "/tmp/{{ gridengine_deb_client }}"
- name: gridengine-exec | get deb file
  get_url:
    url: "http://ftp.jp.debian.org/debian/pool/main/g/gridengine/{{ gridengine_deb_exec }}"
    dest: "/tmp/{{ gridengine_deb_exec }}"

- name: install gridengine-common
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_common }}"
- name: install gridengine-client
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_client }}"
- name: install gridengine-exec
  become: yes
  apt:
    deb: "/tmp/{{ gridengine_deb_exec }}"


- name: set custom hosts script
  become: yes
  copy:
    src: gridengine-get-hostfile.py
    dest: /usr/local/bin/gridengine-get-hostfile.py
    mode: 0755
    force: yes

- name: start gridengine-exec daemon
  service: name=gridengine-exec state=started enabled=yes

- name: update act_qmaster
  become: yes
  template: src=act_qmaster.tmpl dest=/var/lib/gridengine/default/common/act_qmaster mode=0644
  notify: restart gridengine-exec
