---
- include_tasks: gridengine-client-ubuntu1604.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "16.04"

- include_tasks: gridengine-client-ubuntu1804.yml
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == "18.04"


- name: set custom hosts script
  become: yes
  copy:
    src: gridengine-get-hostfile.py
    dest: /usr/local/bin/gridengine-get-hostfile.py
    mode: 0755
    force: yes

- name: start gridengine-exec daemon
  service: name=gridengine-exec state=started enabled=yes

- name: update act_qmaster
  become: yes
  template: src=act_qmaster.tmpl dest=/var/lib/gridengine/default/common/act_qmaster mode=0644
  notify: restart gridengine-exec
