#SPDX-License-Identifier: MIT-0
---
# handlers file for proxmox_gpu

- name: Update grub configuration
  become: yes
  command: update-grub
  listen: update-grub

- name: Update initramfs
  become: yes
  command: update-initramfs -u -k all
  listen: update-initramfs

- name: Reboot system
  become: yes
  reboot:
    msg: "Rebooting to apply GPU passthrough settings"
    delay: 10
  listen: reboot-for-gpu-passthrough
