---
- name: setup nvhpc apt source list
  become: yes
  copy:
    src: nvhpc.list
    dest: /etc/apt/sources.list.d/nvhpc.list  


- name: install nvhpc
  become: yes
  apt:
    name: 
      - nvhpc-22-7
      - environment-modules
    update_cache: yes
    state: latest

     
- name: add nvhpc module
  become: yes
  lineinfile:
    path: /etc/environment-modules/modulespath
    line: "/opt/nvidia/hpc_sdk/modulefiles"



